# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "chipset_resources"
edition.workspace = true
rust-version.workspace = true

[dependencies]
acpi_spec.workspace = true
ipmi_protocol.workspace = true
local_clock.workspace = true
vm_resource.workspace = true

inspect.workspace = true
memory_range.workspace = true
mesh.workspace = true

arbitrary = { workspace = true, optional = true, features = ["derive"] }

[lints]
workspace = true
