# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
edition.workspace = true
name = "snp_test_igvmfilegen"
rust-version.workspace = true

[dependencies]
loader.workspace = true
vmm_core.workspace = true

igvm.workspace = true
igvm_defs.workspace = true
vm_topology.workspace = true
x86defs.workspace = true

anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
crypto = { workspace = true, features = ["native", "vendored"] }
fs-err.workspace = true
hex.workspace = true
serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true, features = ["std"] }
zerocopy.workspace = true

[dev-dependencies]
test_with_tracing.workspace = true

[lints]
workspace = true
