# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "loader_defs"
edition.workspace = true
rust-version.workspace = true

[features]
inspect = ["dep:inspect"]
save_restore = ["dep:memory_range", "dep:mesh_protobuf", "memory_range/mesh"]

[dependencies]
hvdef.workspace = true
open_enum.workspace = true

mesh_protobuf = { workspace = true, optional = true }
memory_range = { workspace = true, optional = true }

bitfield-struct.workspace = true
igvm_defs.workspace = true
static_assertions.workspace = true
zerocopy.workspace = true

# Optional, feature-gated.
inspect = { workspace = true, optional = true }

[lints]
workspace = true
