# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "opentmk_protocol"
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["alloc"] }
thiserror.workspace = true
zerocopy = { workspace = true, features = ["derive"] }

[lints]
workspace = true
