// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Test registration and dispatch.
//!
//! A test binary declares its scenarios with [`opentmk_tests!`](crate::opentmk_tests)
//! and its backends with [`opentmk_backends!`](crate::opentmk_backends), then
//! hands the generated `dispatch` function to [`run_test`] together with the
//! embedded config region.

use opentmk_protocol::OpenTmkConfig;

/// Generates `run_named` to map test names to `exec`. Modules must be declared
/// separately with explicit `mod` statements; per-entry attributes gate the
/// matching dispatch arm.
#[macro_export]
macro_rules! opentmk_tests {
    (
        ctx: $ctx:ty,
        tests: { $( $(#[$meta:meta])* $module:ident ),* $(,)? } $(,)?
    ) => {
        /// Runs the named test. Returns `false` if no such test exists.
        pub fn run_named(test: &str, ctx: &mut $ctx) -> bool {
            match test {
                $(
                    $(#[$meta])*
                    _ if test == stringify!($module) => {
                        $module::exec(ctx);
                        true
                    }
                )*
                _ => false,
            }
        }
    };
}

/// Generates `dispatch` to select a backend, build context, and run the named test.
/// Returns `false` if unknown; entries map names to `|params: &serde_json::Value| -> Ctx`.
#[macro_export]
macro_rules! opentmk_backends {
    ( $( $(#[$meta:meta])* $backend:ident => $build:expr ),* $(,)? ) => {
        fn dispatch(backend: &str, test: &str, params: &::serde_json::Value) -> bool {
            match backend {
                $(
                    $(#[$meta])*
                    _ if backend == stringify!($backend) => {
                        let build = $build;
                        let mut ctx = build(params);
                        $backend::run_named(test, &mut ctx)
                    }
                )*
                _ => false,
            }
        }
    };
}

/// Reads the embedded config and runs the selected backend/test.
///
/// `cfg` is the binary's config region, patched in place by host tooling, and
/// `dispatch` is the function generated by [`opentmk_backends!`](crate::opentmk_backends).
///
/// Panics if the config is missing or invalid, or if it names an unknown
/// backend/test. The config region lives in the test binary so that its
/// dedicated linker section is never garbage collected.
pub fn run_test(cfg: &OpenTmkConfig, dispatch: fn(&str, &str, &serde_json::Value) -> bool) {
    // `black_box` forces an opaque load so the optimizer cannot fold in the empty
    // initializer; host patching happens after build and is invisible to the compiler.
    let cfg = core::hint::black_box(cfg);
    let Some(cfg) = cfg.parse() else {
        panic!("TMK config missing or invalid: binary must be patched with a backend and test");
    };
    if !dispatch(&cfg.backend, &cfg.test, &cfg.params) {
        panic!("unknown backend/test: '{}'/'{}'", cfg.backend, cfg.test);
    }
}
