# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "cxl_spec"
edition.workspace = true
rust-version.workspace = true

[dependencies]
bitfield-struct.workspace = true
inspect.workspace = true
open_enum.workspace = true

[dev-dependencies]
test_with_tracing.workspace = true

[lints]
workspace = true
