# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "underhill_entry"
edition.workspace = true
rust-version.workspace = true

[features]
# Enable per-VM measured product policy support.
product_policy = ["underhill_core/product_policy"]
# Enable gdbstub support.
gdb = ["underhill_core/gdb"]

# Enable profiler support.
profiler = ["underhill_core/profiler"]

# Enable profiler tracing (heap profiling) support.
mem-profile-tracing = ["dep:dhat", "underhill_core/mem-profile-tracing"]

# Enable mimalloc secure mode.
mi-secure = ["mimalloc/secure"]

# Disable secure AVIC support for SNP.
disable_secure_avic = ["underhill_core/disable_secure_avic"]

# Enable vpci support.
vpci = ["underhill_core/vpci"]

# Use the TIO variant of the sev-guest ioctl ABI
dev_snp_tio_guest_ioctl_abi = ["underhill_core/dev_snp_tio_guest_ioctl_abi"]

[target.'cfg(target_os = "linux")'.dependencies]
underhill_core.workspace = true
underhill_init.workspace = true
underhill_crash.workspace = true
underhill_dump.workspace = true

anyhow.workspace = true
fast_memcpy = { workspace = true, features = ["replace_system_memcpy"] }
mimalloc.workspace = true
dhat = { workspace = true, optional = true }

[lints]
workspace = true
