# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "snp_bootshim"
edition.workspace = true
rust-version.workspace = true

[dependencies]
acpi.workspace = true
fdt.workspace = true
igvm_defs.workspace = true
loader_defs.workspace = true
memory_range.workspace = true
minimal_rt.workspace = true
thiserror.workspace = true
x86defs.workspace = true
zerocopy.workspace = true

[dev-dependencies]
test_with_tracing.workspace = true

[build-dependencies]
minimal_rt_build.workspace = true

[lints]
workspace = true
