# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "cca_tests"
edition.workspace = true
rust-version.workspace = true

[[test]]
name = "cca"
harness = false

[dev-dependencies]
petri_artifact_resolver_openvmm_known_paths.workspace = true
petri_artifacts_vmm_test.workspace = true
petri.workspace = true

anyhow.workspace = true
tracing.workspace = true

tempfile.workspace = true

[lints]
workspace = true
