# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "guid"
edition.workspace = true
rust-version.workspace = true

[features]
default = ["std", "getrandom"]
std = ["dep:windows-sys", "dep:windows", "dep:win_etw_provider"]
getrandom = ["dep:getrandom"]
inspect = ["dep:inspect", "std"]
mesh = ["mesh_protobuf", "std"]

[dependencies]
inspect = { workspace = true, optional = true }
mesh_protobuf = { workspace = true, optional = true }

getrandom = { workspace = true, optional = true }
thiserror.workspace = true
zerocopy.workspace = true
[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, optional = true }
windows = { workspace = true, optional = true }
win_etw_provider = { workspace = true, optional = true }

[lints]
workspace = true
