# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "openvmm_hcl"
edition.workspace = true
rust-version.workspace = true

[features]
default = ["tpm"]

# Enable per-VM measured product policy support.
product_policy = ["underhill_entry/product_policy"]

# see the `underhill_entry` crate for more info on these features
gdb = ["underhill_entry/gdb", "openvmm_hcl_resources/debug_worker"]
tpm = [
	"openvmm_hcl_resources/tpm",
	"dep:ms-tpm-20-ref",
	"dep:ms-tcg-tpm-sys",
]
mem-profile-tracing = ["underhill_entry/mem-profile-tracing"]

# Enable mimalloc secure mode.
mi-secure = ["underhill_entry/mi-secure"]

# Disable secure AVIC support for SNP.
disable_secure_avic = ["underhill_entry/disable_secure_avic"]

# Enable vmbus UI devices.
uidevices = ["openvmm_hcl_resources/uidevices", "openvmm_hcl_resources/vnc_worker"]

# Enable NVMe emulation.
nvme = ["openvmm_hcl_resources/nvme", "vpci"]
vpci = ["underhill_entry/vpci"]

# Use the TIO variant of the sev-guest ioctl ABI
dev_snp_tio_guest_ioctl_abi = ["underhill_entry/dev_snp_tio_guest_ioctl_abi"]

[target.'cfg(target_os = "linux")'.dependencies]
underhill_entry.workspace = true
openvmm_hcl_resources.workspace = true
tracing.workspace = true
crypto = { workspace = true, features = ["openssl"] }
# OpenVMM-HCL only needs libcrypto from openssl
openssl_crypto_only.workspace = true

[target.'cfg(all(target_os = "linux", target_env = "musl"))'.dependencies]
# TODO: Change this to symcrypt if the OSS TPM 1.38 can be made to work with it.
ms-tpm-20-ref = { optional = true, workspace = true, features = ["openssl"] }
# TODO: Change this to symcrypt once it's ready.
ms-tcg-tpm-sys = { optional = true, workspace = true, features = ["openssl"] }

[target.'cfg(all(target_os = "linux", not(target_env = "musl")))'.dependencies]
ms-tpm-20-ref = { optional = true, workspace = true, features = ["openssl", "vendored"] }
ms-tcg-tpm-sys = { optional = true, workspace = true, features = ["openssl", "vendored"] }

[package.metadata.xtask.unused-deps]
ignored = [
    # Present to specify TPM backend features
	"ms-tcg-tpm-sys",
	"ms-tpm-20-ref",
    # Present to specify features from flowey
	"tracing",
]

[lints]
workspace = true
